name: Deploy GitHub Pages Site

on:
  # Trigger deployment on pushes to the main branch
  push:
    branches: [ main ]
  
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Checkout football-legend-hub repository
        uses: actions/checkout@v3
        with:
          repository: vedant8211/football-legend-hub
          path: football-legend-hub
          
      - name: Checkout my-indian-states repository
        uses: actions/checkout@v3
        with:
          repository: vedant8211/my-indian-states
          path: my-indian-states
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: '.'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
